### ISSUE TITLE
Array index out of range error when moving trapped colonists in a group

### ISSUE THREAD

**Issue by Mehni** [pardeike/RimWorld-Achtung-Mod#11]
Steps to reproduce:

1. Have a couple of "smart" colonists trapped inside a room. Preferably constructors.
2. Select a group of colonists, some of them free-range, others part of the trapped colonists from step 1.
3. Try moving them as a group in a line.

**Comment by pardeike** [comment]
Cannot reproduce with latest version of Achtung. Please reopen if issue persists.
