### ISSUE TITLE
Freeze because of "started 10 jobs in one tick. newJob=HaulToContainer"

### ISSUE THREAD

**Issue by tobi1449** [pardeike/RimWorld-Achtung-Mod#12]
I've encountered a bug with Achtung where a pawn tries to haul resources to an unfinished building and for some reason stacks the hauling attempts until the game freezes (or produces a stackoverflow errror with another player).

[Hugs Lib log](https://gist.github.com/HugsLibRecordKeeper/00d2d0a34190193a0d37c6908566f4e4) (This is from before the game freezes, obviously I can't upload the log after that)
Savegame that freezes after a few seconds when you undraft the pawns: [Community's Cave Test.zip](https://github.com/pardeike/RimWorld-Achtung-Mod/files/1848255/Community.s.Cave.Test.zip)

Edit: fixed the link for the log file

**Comment by pardeike** [comment]
Good report! I’ve had the 10 jobs error before but my game never crashed because of that. I’ll look into it.

**Comment by pardeike** [comment]
Please verify that the latest version fixes your problem.

**Comment by tobi1449** [comment]
Seems to be fixed, thanks 👍
