### ISSUE TITLE
Clean room not working

### ISSUE THREAD

**Issue by Mythos** [pardeike/RimWorld-Achtung-Mod#2]
I have dug out some parts of the mountain to build a base there.
To clean the new room, I selected the colonists and used "Clean this room". They went inside that room, but then got stuck with "Standing". The same happens with a single colonist.

When I choose a smaller room, it works fine.

OT: Cool ideas so far :+1:

**Comment by Mythos** [comment]
I noticed that this also happens with smaller rooms.
It completely messes the JobGiver up, they are just "Standing" after they cancelled cleaning by themselves.

**Comment by Mythos** [comment]
Every colonist set to clean the room gets this error-spam:

![job error](https://cloud.githubusercontent.com/assets/416568/17659973/760473a0-62d6-11e6-9dcb-b41b89029213.PNG)

**Comment by pardeike** [comment]
I rewrote the whole clean room logic (and added a Fight Fire job too that works outside the home zone). Would you mind to evaluate it again?

**Comment by Mythos** [comment]
Did you already push this to Steam or do I need to download the repo and compile it myself?

**Comment by pardeike** [comment]
Not yet. But the whole GitHub repo is a complete plugin already. Just download it as a zip and put the folder into your Mods folder.

**Comment by pardeike** [comment]
Since this defect was filed the code has changed a lot. So I close this and if it remains a new issue can be opened again.

**Comment by Mythos** [comment]
Didn't notice any problems so far, just some "dusters" (or how they are called - would be Staubwedel in German) moving around the room and I'm not sure if this is intended. :P

**Comment by pardeike** [comment]
Yes it's intended. That symbol is usual used to indicate work at a specific place (which is usually 1 square = 1 job). Since how the whole job is to clean *and* change target I tried to move the symbol code-wise to the new cleaning square too but had no luck with fighting the RimWorld code. So the only option for now is to "show symbol on t

**Comment by pardeike** [comment]
... [pressed button on accident] ...

"show symbol on the way to your goal" which in this case is the point between the colonist and the point you clicked at to clean the room.

**Comment by pardeike** [comment]
And of course great that the command works for you. The old version had lots of reports on colonists become unusable after cleaning and no way to cancel but the new version should behave just fine.

**Comment by Mythos** [comment]
Well this is just a cosmetical issue and I don't mind it. When I saw it first, I thought it is some kind of ghosts cleaning the room to make it faster. :D
Keep up the good work! :+1:
