### ISSUE TITLE
[Suggestion] "Fire At" option that moves colonist in range/LoS of target to shoot at

### ISSUE THREAD

**Issue by septemus** [pardeike/RimWorld-Achtung-Mod#4]
I just feel like this QoL improvement would be great. I don't wish to micromanage everything my colonists do; I have to draft them and then move them in range manually and THEN click "Fire At xx" which I feel like could be improved by this suggestion (unless this does not play into your vision of the mod, then I'll just deal with it). If this is the wrong place for a suggestion, let me know where I should put it and I will gladly do so.

Thanks.

**Comment by pardeike** [comment]
As with the other options I offer, the difficulty lies in doing things without asking the user about options. I had this idea before but am not totally sure about how it would behave exactly. I.e. should it move the colonist back if the enemy is moving closer? Or how should this work with multiple enemies. I guess a simple version with a single enemy per colonist would be a good start and it would move just close enough to get within the own firing range. Then after every shot it would decide to move a bit or to continue shooting. 

Any thoughts?

**Comment by septemus** [comment]
That would be a great start. My main gripe, I guess, with the current system is how I need to order them while they are drafted to move in range while avoiding obstacles to the shot instead of telling them: "oh, just walk out the front door and it'll be on your right. You have a sniper so you should only need to get a clear LoS on them". The reason I suggested this was not for engaging enemies or groups of them, but rather to put down the downed animals from manhunter packs, or useless hostiles wounded on the ground. If there's anything I can do to help (despite my lack of C# knowledge), let me know and I'd be glad to do what I can (eg testing your ideas).

**Comment by pardeike** [comment]
Great. The biggest help I can get is to define exactly how a first version would behave. Since you're probably a more experienced player this would help tremendously. I'll do the coding :)

**Comment by septemus** [comment]
This is how I see the prototype behaving, before it gets fully fleshed out:
Colonist "Taz", Colonist "Kate", and Colonist "Grimm" are all in a colony together (mid-end game). Suddenly, a manhunting pack of Thrumbos show up. Luckily for the colonists, their base has a killbox with turrets set up. However, this killbox is the only way in or our of their base. So they just relax in the base, wander around, eat, sleep, etc., as the turrets do their job. Now, the manhunters are all dead, with a few just writhing on the ground in pain. Taz is in his room meditating, Kate is still sleeping, and Grimm is wandering around. I select Grimm and tell him to go shoot the few remaining Thrumbos to put them out of their misery. He complies and begins his hunt. The first few die relatively easy (because they were in the killbox), but the precision turrets that had also been set up had maimed a few across the map. Luckily for Grimm, his sniper has the most high-tech scope ever manufactured and his range is the whole map. So I right click on an injured Thrumbo on the south-side of the map, and order him to "Fire At Thrumbo". He obliges again and maneuvers into a position where he can see the Thrumbo. He fires a few shots, misses the first 2 and the 3 ends it. 

As opposed to maneuvering him around the giant rock stuck conveniently between his LoS and the dying Thrumbo. Sure, I could still order him to fire and wait a few years before he destroys the rock in the middle, but I'd rather him move around himself.

Hope that scenario paints a picture of how I imagine it working.
I just had another idea though: maybe the ability to designate downed anything as hunt-able? Since the AI automagically maneuvers them while hunting... Though I feel like that would be out of scope for this mod. Maybe I'll mess around if you agree that solution is unrelated/does not fit into your idea.

Sorry for the wall of text :P

**Comment by pardeike** [comment]
Haha, awesome description. I think I can work with that.

**Comment by pardeike** [comment]
I added auto combat so I will close this issue while you can test if this satisfies your needs. You can open this at any time if you think that auto combat is not what you had in mind.

**Comment by septemus** [comment]
So far so good. Sometimes the autopositioner chooses something further away than the original position (even though it could still shoot/hit from that original position). I could be wrong (that they could hit the person) because it seems you left debug mode on/the red tiles to show range of weapon.

**Comment by pardeike** [comment]
The auto combat is still work in progress. It prefers "safe" positions and searches for best cover. It does not handle non-aggressive opponents well as you see because it always prefers the longest possible range. interestingly, it calculates the hit chance and it does not increase with closer shooting so maybe it should stay like that.

The red tiles stay on for now until I build in an option to turn them on/off. Remember: this is a tricky feature that is probably buggy as hell.

**Comment by septemus** [comment]
Yeah no worries, just thought it was an artifact of debugging being
enabled. I'm taking a break from RimWorld until the genius(es) over at CCL
get it up and running for A15. Quite a few mods I use that require CCL
(haven't checked if they've just gone for it and removed/implemented their
own whatevers). However, it seems like a solid feature thus far minus a few
quirks. Good work!
