### ISSUE TITLE
Drafted Colonists Cannot Be Ordered to Move into Room?

### ISSUE THREAD

**Issue by maarxx** [pardeike/RimWorld-Achtung-Mod#7]
Just got the mod. Trying it for first time.

I select a bunch of colonists and draft them. I want to move them places. Normal stuff.

Outdoors, it seems to work fine. Right-click to cluster-move. Right-click-and-drag to order them into a line. Cool stuff. Very neat. I like the feature.

But I cannot seem to order them into a room. When I right click, I only get popup float menu with option "Clean room x#". I cannot figure out how to get them to just walk into the room.

If it's relevant, I use numeric priorities, and all my pawns have a number assigned to Cleaning (a low number).

**Comment by maarxx** [comment]
Reread the description carefully and saw that holding ALT suppresses the context menu. This is acceptable workaround.

Checked the Comments on Steam Workshop and saw you said there's a preferences menu (SHIFT+RETURN). Preferences menu is nice. The preferences menu itself isn't mentioned anywhere in the description?

Saw that within the preferences menu, I can check "Reverse context menu key" to suppress the context menu unless I hold ALT, which gives me the nice right-click-and-drag-into-a-line option without the clean room spam.

This is functional setup for now, but still worth considering whether it is intentional that simple movement is prohibited by clean room option?

**Comment by pardeike** [comment]
You cannot have both: menu and positioning at the same time. So this is expected behavior. Also, the mod displays its version and the note about shift-return during map start in the upper left corner.
