### ISSUE TITLE
[Suggestion] Drag Arc or Semi-Circle

### ISSUE THREAD

**Issue by maarxx** [pardeike/RimWorld-Achtung-Mod#8]
Hi! Loving the mod! It's awesome!

One new feature suggestion: Even better than dragging colonists into a line, would be dragging colonists into an arc or semi-circle.

Semi-circle around a target area is a very common layout, I think, but very click-intensive to do by hand.

**Comment by maarxx** [comment]
Interaction could be - specify origin, specify radius, specify arc start angle, specify arc end angle.

**Comment by pardeike** [comment]
Replaced bydrag-in-formation functionality. I know it's not the same but good enough in my opinion.
